# Generated by Django 6.0.6 on 2026-06-22 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=500)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='stores_stor_name_988b60_idx')],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='products.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='stores.store')),
            ],
            options={
                'indexes': [models.Index(fields=['store', 'product'], name='stores_inve_store_i_83f0cf_idx'), models.Index(fields=['quantity'], name='stores_inve_quantit_d2778a_idx')],
                'unique_together': {('store', 'product')},
            },
        ),
    ]
